---
- name: Setup Docker on EC2
  hosts: web
  become: yes
  tasks:
    - name: Update APT packages
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: yes
        state: started

